version: 2.1

orbs:
  python: circleci/python@0.3.2
  codecov: codecov/codecov@1.0.2

jobs:
  quality_checks:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Quality Checks
          command: |
            pyenv install 3.6.9
            poetry install -E all
            make lint
            make test-ci
      - codecov/upload:
          file: ${PWD}/test-results/coverage.xml
      - store_test_results:
          path: test-results
  generate_docs:
    executor: python/default
    steps:
      - run:
          name: Check Publish Eligibility
          command: |
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              echo "Semver deploy detected. Proceeding to build and publish docs."
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Master build detected. Proceeding to build and publish docs."
            else
              echo "Not a master/semver ref. Skipping documentation build."
              circleci-agent step halt
            fi
      - checkout
      - run:
          name: Generate Docs
          command: |
            make docs-build-docker
      - run:
          name: Publish Docs
          command: |
            echo "Todo!"
workflows:
  version: 2
  ci:
    jobs:
      - quality_checks
      - generate_docs:
          requires:
            - quality_checks
