version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  install:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install
          command: poetry install
  quality_checks:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Quality Checks
          command: |
            make test
workflows:
  version: 2
  ci:
    jobs:
      - install
      - quality_checks:
          requires:
            - install
