version: 2.1

orbs:
  python: circleci/python@0.3.2
  codecov: codecov/codecov@1.0.2

jobs:
  quality_checks:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Quality Checks
          command: |
            poetry install
            make lint
            make test-ci
      - codecov/upload:
          file: ${PWD}/test-results/coverage.xml
      - store_test_results:
          path: test-results
workflows:
  version: 2
  ci:
    jobs:
      - quality_checks
