version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  quality_checks:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Quality Checks
          command: |
            poetry install
            make lint
            make test
workflows:
  version: 2
  ci:
    jobs:
      - quality_checks
