version: 2.1

orbs:
  python: circleci/python@0.3.2
  codecov: codecov/codecov@1.0.2

# Reusable YAML fragments
setup_remote_docker: &setup_remote_docker
  setup_remote_docker:
    docker_layer_caching: true

main_env: &main_env
  docker:
    - image: circleci/buildpack-deps:buster
  environment:
    AWS_DEFAULT_REGION: "us-west-2"

jobs:
  quality_checks:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Quality Checks
          command: |
            pyenv install 3.6.9
            poetry install -E all
            make lint
            make test-ci
      - codecov/upload:
          file: ${PWD}/test-results/coverage.xml
      - store_test_results:
          path: test-results
  generate_docs:
    <<: *main_env
    steps:
      - checkout
      - *setup_remote_docker
      - run:
          name: Generate Docs
          command: |
            make docs-build-docker
      - run:
          name: Publish Docs
          command: |
            UPLOAD_PREFIX="test"
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              UPLOAD_PREFIX="${CIRCLE_TAG}"
              echo "Semver tag detected. Publishing docs accordingly."
            fi
            echo "Publishing documentation for ${UPLOAD_PREFIX}"
            docker run --rm \
              --entrypoint /bin/bash \
              -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
              -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
              -v $(pwd)/sdocs/dist/:/tmp/dist/ \
              leaflinkengineering/llp-awscli:0.3.0 \
              -c "aws s3 cp /tmp/dist/html/ s3://${S3_BUCKET_PYLL_ERRORS_DOCS}/json-errors/${UPLOAD_PREFIX}/ --recursive --acl public-read"

workflows:
  version: 2
  ci:
    jobs:
      - quality_checks:
          filters:
            branches:
              only: master
            tags:
              only: /\d{1,}[.]\d{1,}[.]\d{1,}/
      - generate_docs:
          context: s3-doc-publishing
          # requires:
          #   - quality_checks
          # filters:
          #   branches:
          #     only: master
          #   tags:
          #     only: /\d{1,}[.]\d{1,}[.]\d{1,}/
