name: llp-ci

on:
  push:
  pull_request:
  release:
    types: [published]

env:
  PR_NUMBER: ${{ github.event.number }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  quality-checks:
    strategy:
      matrix:
        python-version: [3.6]
        poetry-version: [1.1.13]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Lint Code
        run: make lint && make test-ci
