name: llp-ci

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

env:
  PR_NUMBER: ${{ github.event.number }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}
  POETRY_VERION: 1.1.13
  PYTHON_VERSION_MIN: 3.6

jobs:
  quality-checks:
    strategy:
      matrix:
        python-version: [ 3.6 ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.POETRY_VERION }}
      - name: Install Dependencies
        run: poetry install -E all
      - name: Lint Code
        run: make lint
      - name: Test Code
        run: make test-ci
  generate-docs:
    runs-on: ubuntu-latest
    if:  github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION_MIN }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.POETRY_VERION }}
      - name: Install Dependencies
        run: poetry install -E all
      - name: Build Docs
        run: |
          rm -rf ./sdocs/dist || true
          make docs-build
      - name: Publish Docs
        run: |
          UPLOAD_PREFIX="stable"
          if [[ ! -z "${RELEASE_TAG}" ]]; then
            UPLOAD_PREFIX="${RELEASE_TAG}"
            echo "Semver tag detected. Publishing docs accordingly."
          fi
          echo "Publishing documentation for ${UPLOAD_PREFIX}."
