name: lint-pr-title

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

permissions:
  id-token: write
  issues: write
  pull-requests: write

jobs:
  lint:
    secrets: inherit
    uses: leaflink/ci-tools/.github/workflows/lint-pr-title.yml@main
