name: release

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LeafLink/ci-tools/python-release@main
        with:
          aws-role-arn: arn:aws:iam::642296112925:role/llp-gha-writer
          aws-codeartifact-repo: leaflink-pypi
